name: Lau Deisgns
favicon: null
layout_spectrum: 0.76058
typography_spectrum: 0.60368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#070616'
    - '#95269c'
    - '#2f329b'
    - '#d0aea2'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
